media:
  - name: writing_images
    label: Writing images
    input: public/images/writing
    output: /images/writing
    categories: [image]
    rename: safe

content:
  - name: writing
    label: Writing
    type: collection
    path: src/content/writing
    format: yaml-frontmatter
    filename: "{primary}.md"
    subfolders: false
    operations:
      create: true
      rename: false
      delete: true
    view:
      fields: [title, pubDate, draft]
      primary: title
      sort: [pubDate, title]
      search: [title, description, tags]
      default:
        sort: pubDate
        order: desc
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        required: true
      - name: pubDate
        label: Publication date
        type: date
        required: true
        options:
          format: yyyy-MM-dd
      - name: tags
        label: Tags
        type: string
        list: true
      - name: draft
        label: Draft
        type: boolean
        default: false
      - name: body
        label: Body
        type: rich-text
        required: true
        options:
          format: markdown
          switcher: true
          media: writing_images
